### ISSUE TITLE
[SCM-121] Intermittent CVS test failures

### ISSUE THREAD

**Issue by olamy** [olamy/maven-scm#34]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** opened **[SCM-121](https://issues.apache.org/jira/browse/SCM-121?redirect=false)** and commented

Dan and I continue to have test failures when trying to compile the cvs plugin in our environment.  I emailed these problems to the scm-dev list about a week ago.

---

**Affects:** 1.0-beta-3

**Attachments:**
- [cvs.exe](https://issues.apache.org/jira/secure/attachment/12718685/cvs.exe) (_908.11 kB_)

**Issue Links:**
- [SCM-29](https://issues.apache.org/jira/browse/SCM-29) test with CVS NT

**Comment by olamy** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

I fixed the test failure reported by Dennis above.  There are still failures in the Diff TCK test case.  I can't figure out why they are breaking but I am running an old version of CVS (1.11.5).

**Comment by olamy** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

I tried to issue the cvs command on the command line and got back the same error as when it was run from maven.

To see is this is a Windows issue, I zipped my cvs-provider directory and put it on a Solaris machine. I then ran the same command line cvs command there, and it produced the exact same error message. The Solaris machine has "Concurrent Versions System (CVS) 1.11.20 (client/server)" from FSF.

Is there someone who is able to run the tests for the cvs-provider?

**Comment by olamy** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

diff command test always fail on my pc ( xp, java5, cygwin cvs), but passes on other machines ;(

---

Battery: org.apache.maven.scm.provider.cvslib.command.diff.CvsDiffCommandTckTest

---

Tests run: 1, Failures: 1, Errors: 0, Time elapsed: 3.609 sec

testDiffCommand(org.apache.maven.scm.provider.cvslib.command.diff.CvsDiffCommandTckTest)  Time elapsed: 3.609 sec  <<< FAILURE!

[ stdout ] ---------------------------------------------------------------

[INFO] Executing: cvs -q -f diff -u -N
[INFO] Working directory: C:\dev\maven\src\scm\maven-scm-providers\maven-scm-provider-cvs\target\scm-test\working-copy

[ stderr ] ---------------------------------------------------------------

[ stacktrace ] -----------------------------------------------------------

junit.framework.ComparisonFailure: expected:<@@ -0,0 +1 @@
+/src/main/java/org/Foo.java
\ No newline at end of file

> but was:<>
> at junit.framework.Assert.assertEquals(Assert.java:81)
> at junit.framework.Assert.assertEquals(Assert.java:87)
> at org.apache.maven.scm.tck.command.diff.DiffCommandTckTest.testDiffCommand(DiffCommandTckTest.java:214)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)

**Comment by olamy** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

it's very strange, but i can't help on this error because i can't reproduce it.

**Comment by olamy** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

Do you have always failures on cvs tests? Is it only for the diff command?

Can you run manually commands that run by maven-scm? tell me what is the result. For the diff result, is it really an empty string or a problem with carriage return?
I try it under windows with cvsnt and cygwin cvs (default end lines for cygwin are defined as unix end lines)

**Comment by olamy** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

Tests works fine with your cvs.exe

**Comment by olamy** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

Weird.  I wonder if it's a cygwin binary and your cygwin1.dll is different enough to not display the bad behavior we are seeing?

**Comment by olamy** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

Info about my cygwin1.dll:
v ersion: 1005.19.0.0
Build date : 2006-01-20 13:28

**Comment by olamy** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

I checked and it looks like that binary is static.  So I have no idea why it's not working.  I'm out of ideas.

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
